from pathlib import Path
from html import escape
folder=Path('.archify/workflow-health-journal-agentic-20261002-213000')
parts=[]
def add(s): parts.append(s)
add('''<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="1740" viewBox="0 0 1280 1740" role="img" aria-labelledby="title desc"><title id="title">Health Journal — 受控 Agent 工作流</title><desc id="desc">患者原文先保存，读取上下文并检查紧急提示。DeepSeek 规划，代码核验后选择追问、结束本轮或生成摘要。患者核对后保存，就诊结果归档并供下次调用。A、B、X 标识跨区域的流程续接。</desc><defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0 0L10 5L0 10Z" fill="#79695e"/></marker><marker id="redArrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0 0L10 5L0 10Z" fill="#a8543c"/></marker><style>text{font-family:Arial,'PingFang SC','Microsoft YaHei',sans-serif;fill:#3d3834}.title{font-size:32px;font-weight:600}.body{font-size:16px;fill:#70655c}.label{font-size:14px;fill:#746458}.node-title{font-size:21px;font-weight:600}.node-sub{font-size:15px;fill:#6c625a}.code{font-size:12px;letter-spacing:.6px;fill:#956f58}.edge{fill:none;stroke:#79695e;stroke-width:2;marker-end:url(#arrow);stroke-linejoin:round}.red{stroke:#a8543c;marker-end:url(#redArrow)}.connector{fill:#f2e5d8;stroke:#b58b6f;stroke-width:1.5}.badge{font-size:13px;font-weight:bold;fill:#8a573c}</style></defs><rect width="1280" height="1740" fill="#faf7f2"/><text x="64" y="66" class="title">Health Journal · 受控 Agent 工作流</text><text x="64" y="101" class="body">观察 → 规划 → 执行 → 核验 → 保存状态 · v1 · 总控 Agent + 专用工具</text>''')
def node(id,x,y,title,sub,code,fill='#ffffff',height=120):
 add(f'<g id="{id}"><rect x="{x}" y="{y}" width="320" height="{height}" rx="17" fill="{fill}" stroke="#d9cec2"/><text x="{x+22}" y="{y+28}" class="code">{escape(code)}</text><text x="{x+22}" y="{y+61}" class="node-title">{escape(title)}</text>')
 for i,line in enumerate(sub):add(f'<text x="{x+22}" y="{y+89+i*21}" class="node-sub">{escape(line)}</text>')
 add('</g>')
def edge(d,label=None,x=0,y=0,red=False):
 add(f'<path d="{d}" class="edge{" red" if red else ""}"/>')
 if label:add(f'<text x="{x}" y="{y}" class="label">{escape(label)}</text>')
def circle(x,y,letter,label=None):
 add(f'<circle cx="{x}" cy="{y}" r="17" class="connector"/><text x="{x}" y="{y+5}" text-anchor="middle" class="badge">{letter}</text>')
 if label:add(f'<text x="{x+27}" y="{y+5}" class="label">{escape(label)}</text>')
node('input',64,160,'患者记录，先保存原文',['建档 / 新症状 / 后续变化'],'01 · OBSERVE / SAVE')
node('context',480,160,'读取本次上下文',['档案 + 当前事件 + 选定历史'],'02 · READ_CONTEXT')
node('safety',896,160,'本地紧急提示检查',['命中保守规则时优先提示求助'],'03 · SAFETY_CHECK', '#fbf0e8')
edge('M384 220H480');edge('M800 220H896')
circle(70,133,'A');circle(486,133,'B')
add('<rect x="896" y="326" width="320" height="62" rx="13" fill="#f4dfd6"/><text x="916" y="352" class="node-sub">提示立即寻求专业帮助</text><text x="916" y="374" class="code">urgent · 不等模型，不作诊断</text>')
edge('M1216 220H1248V357H1216','命中',1210,310,True)
edge('M1056 280V300H848V350H224V420','未命中规则',616,340)
node('plan',64,420,'总控 Agent 提出下一步',['DeepSeek：事实 + 缺失信息 + 动作'],'04 · EXTRACT_AND_PLAN','#edf0e6')
node('verify',480,420,'代码核验计划与引用',['原文精确匹配 / 目标匹配 / 白名单'],'05 · VERIFY_SOURCES','#fbf0e8')
node('route',896,420,'调用获准的专用工具',['只允许下方三种动作'],'06 · EXECUTE_TOOL')
edge('M384 480H480','结构化 JSON',391,465);edge('M800 480H896','校验通过',810,465)
circle(362,402,'X');circle(778,402,'X')
edge('M1056 540V610H224V690','缺少有用描述',247,600)
edge('M1056 610H640V690','本轮足够',652,642)
edge('M1056 610V690','患者请求摘要',1070,650)
node('question',64,690,'提出一个澄清问题',['等待患者回答，下一次再运行'],'ASK_FOLLOWUP · waiting_patient','#edf0e6')
node('finish',480,690,'结束本轮记录',['不重复提问；随时可以再记录'],'FINISH_TRACKING · completed')
node('brief',896,690,'生成可编辑摘要',['时间线、健康背景、已选历史'],'CREATE_BRIEF · waiting_review','#edf0e6')
edge('M224 810V886');edge('M1056 810V886')
node('reply',64,886,'患者补充 / 更正',['新原文保存后再判断下一步'],'HUMAN · 答案属于患者')
node('review',896,886,'患者逐字核对',['可修改草稿；明确确认后才保存'],'HUMAN · 审阅与决定')
edge('M224 1006V1050');circle(224,1068,'A','续接上方：先保存原文')
edge('M1056 1006V1110','患者确认',1070,1054)
node('checkpoint',896,1110,'保存版本与来源快照',['记录审核完成；可 PDF / 复制 / 展示'],'SAVE_REVIEWED_BRIEF · completed')
edge('M1056 1230V1280','就诊之后',1070,1260)
node('visit',896,1280,'患者录入就诊结果',['医生结论、处理方案、后续安排'],'CLINICIAN OUTCOME · 患者自行录入')
node('history',480,1280,'归档，供以后关联',['下次出现类似情况，由患者选用'],'MEMORY · 历史不是本次诊断')
edge('M896 1340H800','归档',832,1325)
edge('M640 1400V1438');circle(640,1456,'B','续接上方：读取选定历史')
add('<rect x="64" y="1130" width="704" height="100" rx="17" fill="#f3e7df" stroke="#dbc8ba"/>')
circle(99,1161,'X');add('<text x="128" y="1168" class="node-title">校验失败、模型错误或服务中断</text><text x="88" y="1201" class="node-sub">保存安全错误与已完成步骤；原文不丢失。用户重试 → 新运行关联旧运行。</text>')
add('<text x="64" y="1495" class="label">A / B / X 为跨区域续接标识；等待患者的节点不会在后台擅自继续。</text>')
add('<rect x="64" y="1520" width="1152" height="170" rx="18" fill="#efece5"/>')
for y,title,body in [(1554,'统一运行合同','runId · goal · sourceFingerprint · steps · status · output / error · parentRunId'),(1598,'可靠性规则','同源请求幂等；来源变化需重新核对；重启中断可重试；仅记录外部动作与结果。'),(1642,'本代边界','单机 SQLite，英文 / 中文；不作诊断，不自动发送；邮件及关机后定时服务尚未接入。')]:
 add(f'<text x="88" y="{y}" class="badge">{title}</text><text x="88" y="{y+22}" class="node-sub">{body}</text>')
add('</svg>')
svg=''.join(parts)
(folder/'health-journal-agentic.svg').write_text(svg)
Path('health-journal/public/workflow-design.svg').write_text(svg)
css='''*{box-sizing:border-box}body{margin:0;background:#faf7f2;color:#3d3834;font:16px/1.7 system-ui,-apple-system,"PingFang SC",sans-serif}main{max-width:1320px;margin:auto;padding:28px 24px 50px}header{display:flex;gap:24px;align-items:center;justify-content:space-between;flex-wrap:wrap}h1{font:32px/1.3 Georgia,serif;margin:0}p{color:#71675f}a{color:#92583f}nav{display:flex;gap:20px}.diagram{width:100%;display:block;margin:24px 0;border:1px solid #e1d6ca;border-radius:16px}details{border:1px solid #e1d6ca;border-radius:14px;padding:16px 22px;background:white;margin-top:12px}summary{cursor:pointer;font-weight:600}code{background:#f4eee7;padding:1px 5px;border-radius:4px}li{margin:8px 0}@media(max-width:600px){main{padding:20px 12px}h1{font-size:27px}.diagram-wrap{overflow:auto}.diagram{min-width:900px}nav{font-size:14px}}'''
body='''<header><div><h1>Health Journal / Agentic workflow</h1><p>已选架构 A · 受控总控 Agent + 专用工具 · 设计版本 1.0</p></div><nav><a href="/">返回网站</a><a href="workflow-design.svg" download="health-journal-agentic.svg">下载 SVG 设计图</a></nav></header><div class="diagram-wrap"><img class="diagram" src="workflow-design.svg" alt="Health Journal 受控 Agent 完整工作流设计图"></div><details open><summary>这套流程的标准化约定</summary><ul><li>每次运行具有固定目标、唯一编号、来源指纹和步骤事件，出错可追踪、可重试。</li><li>模型只提出 <code>ask_followup</code>、<code>finish_tracking</code>、<code>create_brief</code>；代码按目标限制动作并验证原文引用。</li><li>患者回答与患者审阅是流程的暂停点。待核对草稿可以恢复，未经患者确认不会变成已核对版本。</li><li>保存临床记录与保存运行轨迹分开，审计动作不会无故改变临床来源版本。</li></ul></details><details><summary>如何阅读与验证</summary><p>图中的 A / B / X 是跨区域续接标识，避免长回路线遮挡主流程。此图为逻辑设计合同；实现文件、测试命令和浏览器验证结果见项目的 AGENTIC-WORKFLOW.md。原始 Archify 候选与失败诊断一同保留；最终 SVG 使用显式布局，未声称通过 Archify 自动布局认证。</p></details>'''
Path('health-journal/public/workflow-design.css').write_text(css)
Path('health-journal/public/workflow-design.html').write_text('<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Health Journal · Agent 工作流设计</title><link rel="stylesheet" href="workflow-design.css"><main>'+body+'</main></html>')
# A standalone deliverable embeds both styling and the vector diagram; no server is required.
import base64
svg_url='data:image/svg+xml;base64,'+base64.b64encode(svg.encode()).decode()
offline_body=body.replace('src="workflow-design.svg"',f'src="{svg_url}"').replace('href="workflow-design.svg"',f'href="{svg_url}"').replace('href="/"','href="http://127.0.0.1:4187/"')
(folder/'health-journal-agentic.html').write_text('<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Health Journal · Agent 工作流设计</title><style>'+css+'</style><main>'+offline_body+'</main></html>')
print('Saved HTML, SVG, and source to',folder)
